apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: inject-response-header
spec:
  match: api.definition == "helloworld" && 
         api.gateway    == "helloworld-gold" && 
         api.operation  == "SayHello"
  actions:
  responseHeaderOperations:
  - name: x-api-response
    values:
    - '"true"'
