apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: inject-response-header
spec:
  # this would be using attributes intead of headers in the real world
  match: request.headers["api.definition"] == "helloworld" && 
         request.headers["api.gateway"]    == "helloworld-gold" && 
         request.headers["api.operation"]  == "SayHello"
  actions:
  responseHeaderOperations:
  - name: x-api-response
    values:
    - '"true"'
 