apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: api-helloworld-com
spec:
  gateways:
  - helloworld-gateway
  - mesh
  hosts:
  - api.helloworld.com
  http:
  - match:
    - uri:
        exact: /hello
    route:
    - destination:
        host: blackhole
