apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: api-inject-header
spec:
  filters:
  - listenerMatch:
      listenerType: SIDECAR_INBOUND
      listenerProtocol: HTTP
    insertPosition:
      index: AFTER
      relativeTo: envoy.router
    filterName: envoy.lua
    filterType: HTTP
    filterConfig:
      inlineCode: |
          -- api-inject-header --
            
          function envoy_on_response(request_handle)
          
            headers = request_handle:headers()
            headers:replace("x-api-response", "true")
            
            -- request_handle:logCritical("inject header")
          end
